name: Islam786
description: Daily islamic activities

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.2+10

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  sqflite:
  path:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: "^0.1.2"
  shared_preferences: "^0.5.8"
  hijri: "^2.0.2"
  http: "^0.12.2"
  geolocator: "^5.3.2+2"
  android_intent: "^0.3.7+2"
  url_launcher: "^5.5.0"
  toast: "^0.1.5"
  share: "^0.6.4+3"
  firebase_messaging: "^6.0.16"
  flutter_local_notifications: "^1.4.4+2"
  audioplayers: "^0.15.1"
  connectivity: "^0.4.9"


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/content/names99/99namesmola.json
    - assets/content/names99/
    - assets/content/_dua.json
  fonts:
    - family: NoorQuran
      fonts:
        - asset: assets/fonts/saleem.ttf
