class HadithData{
  static var _ref = [
    "Narrated by Abu Huraira","Narrated by 'Abdullah bin 'Amr","Narrated by Ibn 'Umar","Narrated by Ibn 'Umar","Narrated by 'Abdullah bin Abbas","Narrated by Anas bin Malik","Narrated by Abu Waqid Al-Laithi","Narrated by 'Abdur Rahman bin Abi Bakra's father","Narrated by Ibn Mas'ud","Narrated by Anas bin Malik","Narrated by Abu Wail","Narrated by Muawiya","Narrated by Ibn 'Umar","Narrated by 'Abdullah bin Mas'ud","Narrated by Ibn 'Abbas","Narrated by Ibn 'Abbas","Narrated by Ibn 'Abbas","Narrated by Mahmud bin Rabi'a","Narrated by Ibn 'Abbas","Narrated by Abu Musa","Narrated by Anas","Narrated by Anas","Narrated by Ibn 'Umar","Narrated by 'Abdullah bin Amr bin Al 'Aas","Narrated by Ibn 'Abbas","Narrated by Abu Huraira","Narrated by Asma","Narrated by 'Abdullah bin Abi Mulaika","Narrated by 'Umar","Narrated by Abu Mas'ud Al-Ansari","Narrated by Zaid bin Khalid Al-Juhani","Narrated by Abu Musa","Narrated by Anas bin Malik","Narrated by Anas","Narrated by Anas","Narrated by 'Abdullah bin 'Amr","Narrated by Abu Burda's father","Narrated by Ibn 'Abbas","Narrated by Abu Huraira","Narrated by Abdullah Ibn Dinar","Narrated by 'Abdullah bin 'Amr bin Al' As","Narrated by Abu Said Al-Khudri","Narrated by Abu Said Al-Khudri","Narrated by Ibn Abu Mulaika","Narrated by Abu Bakra","Narrated by 'Ali","Narrated by 'Abdullah bin Az-Zubair","Narrated by Anas","Narrated by Salama","Narrated by Abu Huraira","Narrated by Ash-Sha'bi","Narrated by Abu Huraira","Narrated by 'Ubaidullah bin 'Abdullah","Narrated by Um Salama","Narrated by 'Abdullah bin 'Umar","Narrated by Ibn 'Abbas","Narrated by Abu Huraira","Narrated by Ibrahim bin Al-Mundhir","Narrated by Abu Huraira","Narrated by Jarir","Narrated by Said bin Jubair","Narrated by Abu Musa","Narrated by 'Abdullah bin 'Amar","Narrated by Aswad","Narrated by Abu At-Tufail","Narrated by Anas","Narrated by Um Salama","Narrated by 'Abdullah bin 'Umar","Narrated by 'Ali","Narrated by Nafi","Narrated by Ibn 'Umar"
  ];

  static int hadithLength = _ref.length;

  static var _hadith = [
    "While the Prophet was saying something in a gathering, a Bedouin came and asked him, \"When would the Hour (Doomsday) take place?\" Allah's Apostle continued his talk, so some people said that Allah's Apostle had heard the question, but did not like what that Bedouin had asked. Some of them said that Alllah's Apostle had not heard it. When the Prophet finished his speech, he said, \"Where is the questioner, who enquired about the Hour (Doomsday)?\" The Bedouin said, \"I am here, O Allah's Apostle .\" Then the Prophet said, \"When honesty is lost, then wait for the Hour (Doomsday).\" The Bedouin said, \"How will that be lost?\" The Prophet said, \"When the power or authority comes in the hands of unfit persons, then wait for the Hour (Doomsday.)\" "
    ,"Once the Prophet remained behind us in a journey. He joined us while we were performing ablution for the prayer which was over-due. We were just passing wet hands over our feet (and not washing them properly) so the Prophet addressed us in a loud voice and said twice or thrice: \"Save your heels from the fire.\" "
    ,"Allah's Apostle said, \"Amongst the trees, there is a tree, the leaves of which do not fall and is like a Muslim. Tell me the name of that tree.\" Everybody started thinking about the trees of the desert areas. And I thought of the date-palm tree but felt shy to answer the others then asked, \"What is that tree, O Allah's Apostle ?\" He replied, \"It is the date-palm tree.\" "
    ,"The Prophet said, \"Amongst the trees, there is a tree, the leaves of which do not fall and is like a Muslim. Tell me the name of that tree.\" Everybody started thinking about the trees of the desert areas. And I thought of the date-palm tree. The others then asked, \"Please inform us what is that tree, O Allah's Apostle?\" He replied, \"It is the date-palm tree.\" "
    ,"Once Allah's Apostle gave a letter to a person and ordered him to go and deliver it to the Governor of Bahrain. (He did so) and the Governor of Bahrain sent it to Chousroes, who read that letter and then tore it to pieces. (The sub-narrator (Ibn Shihab) thinks that Ibn Al-Musaiyab said that Allah's Apostle invoked Allah against them (saying), \"May Allah tear them into pieces, and disperse them all totally.)\" "
    ,"Once the Prophet wrote a letter or had an idea of writing a letter. The Prophet was told that they (rulers) would not read letters unless they were sealed. So the Prophet got a silver ring made with \"Muhammad Allah's Apostle\" engraved on it. As if I were just observing its white glitter in the hand of the Prophet ."
    ,"While Allah's Apostle was sitting in the mosque with some people, three men came. Two of them came in front of Allah's Apostle and the third one went away. The two persons kept on standing before Allah's Apostle for a while and then one of them found a place in the circle and sat there while the other sat behind the gathering, and the third one went away. When Allah's Apostle finished his preaching, he said, \"Shall I tell you about these three persons? One of them be-took himself to Allah, so Allah took him into His grace and mercy and accommodated him, the second felt shy from Allah, so Allah sheltered Him in His mercy (and did not punish him), while the third turned his face from Allah and went away, so Allah turned His face from him likewise. \" "
    ,"Once the Prophet was riding his camel and a man was holding its rein. The Prophet asked, \"What is the day today?\" We kept quiet, thinking that he might give that day another name. He said, \"Isn't it the day of Nahr (slaughtering of the animals of sacrifice)\" We replied, \"Yes.\" He further asked, \"Which month is this?\" We again kept quiet, thinking that he might give it another name. Then he said, \"Isn't it the month of Dhul-Hijja?\" We replied, \"Yes.\" He said, \"Verily! Your blood, property and honor are sacred to one another (i.e. Muslims) like the sanctity of this day of yours, in this month of yours and in this city of yours. It is incumbent upon those who are present to inform those who are absent because those who are absent might comprehend (what I have said) better than the present audience.\" "
    ,"The Prophet used to take care of us in preaching by selecting a suitable time, so that we might not get bored. (He abstained from pestering us with sermons and knowledge all the time). "
    ,"The Prophet said, \"Facilitate things to people (concerning religious matters), and do not make it hard for them and give them good tidings and do not make them run away (from Islam).\" "
    ,"'Abdullah used to give a religious talk to the people on every Thursday. Once a man said, \"O Aba 'Abdur-Rahman! (By Allah) I wish if you could preach us daily.\" He replied, \"The only thing which prevents me from doing so, is that I hate to bore you, and no doubt I take care of you in preaching by selecting a suitable time just as the Prophet used to do with us, for fear of making us bored.\" "
    ,"I heard Allah's Apostle saying, \"If Allah wants to do good to a person, He makes him comprehend the religion. I am just a distributor, but the grant is from Allah. (And remember) that this nation (true Muslims) will keep on following Allah's teachings strictly and they will not be harmed by any one going on a different path till Allah's order (Day of Judgment) is established.\" "
    ,"We were with the Prophet and a spadix of date-palm tree was brought to him. On that he said, \"Amongst the trees, there is a tree which resembles a Muslim.\" I wanted to say that it was the date-palm tree but as I was the youngest of all (of them) I kept quiet. And then the Prophet said, \"It is the date-palm tree.\" "
    ,"The Prophet said, \"Do not wish to be like anyone except in two cases. (The first is) A person, whom Allah has given wealth and he spends it righteously; (the second is) the one whom Allah has given wisdom (the Holy Qur'an) and he acts according to it and teaches it to others.\" (Fateh-al-Bari page 177 Vol. 1) "
    ,"That he differed with Hur bin Qais bin Hisn Al-Fazari regarding the companion of (the Prophet) Moses. Ibn 'Abbas said that he was Khadir. Meanwhile, Ubai bin Ka'b passed by them and Ibn 'Abbas called him, saying \"My friend (Hur) and I have differed regarding Moses' companion whom Moses, asked the way to meet. Have you heard the Prophet mentioning something about him? He said, \"Yes. I heard Allah's Apostle saying, \"While Moses was sitting in the company of some Israelites, a man came and asked him. \"Do you know anyone who is more learned than you? Moses replied: \"No.\" So Allah sent the Divine Inspiration to Moses: 'Yes, Our slave Khadir (is more learned than you.)' Moses asked (Allah) how to meet him (Khadir). So Allah made the fish as a sign for him and he was told that when the fish was lost, he should return (to the place where he had lost it) and there he would meet him (Al-Khadir). So Moses went on looking for the sign of the fish in the sea. The servant-boy of Moses said to him: Do you remember when we betook ourselves to the rock, I indeed forgot the fish, none but Satan made me forget to remember it. On that Moses said: 'That is what we have been seeking? (18.64) So they went back retracing their foot-steps, and found Khadir. (And) what happened further to them is narrated in the Holy Qur'an by Allah. (18.54 up to 18.82) "
    ,"Once the Prophet embraced me and said, \"O Allah! Bestow on him the knowledge of the Book (Qur'an).\" "
    ,"Once I came riding a she-ass and had (just) attained the age of puberty. Allah's Apostle was offering the prayer at Mina. There was no wall in front of him and I passed in front of some of the row while they were offering their prayers. There I let the she-ass loose to graze and entered the row, and nobody objected to it. "
    ,"When I was a boy of five, I remember, the Prophet took water from a bucket (used far getting water out of a well) with his mouth and threw it on my face. "
    ,"That he differed with Hur bin Qais bin Hisn Al-Fazari regarding the companion of the Prophet Moses. Meanwhile, Ubai bin Ka'b passed by them and Ibn 'Abbas called him saying, \"My friend (Hur) and I have differed regarding Moses' companion whom Moses asked the way to meet. Have you heard Allah's Apostle mentioning something about him? Ubai bin Ka'b said: \"Yes, I heard the Prophet mentioning something about him (saying) while Moses was sitting in the company of some Israelites, a man came and asked him: \"Do you know anyone who is more learned than you? Moses replied: \"No.\" So Allah sent the Divine Inspiration to Moses: '--Yes, Our slave Khadir is more learned than you. Moses asked Allah how to meet him (Al-Khadir). So Allah made the fish a sign for him and he was told when the fish was lost, he should return (to the place where he had lost it) and there he would meet him (Al-Khadir). So Moses went on looking for the sign of the fish in the sea. The servant-boy of Moses said: 'Do you remember when we betook ourselves to the rock, I indeed forgot the fish, none but Satan made me forget to remember it. On that Moses said, 'That is what we have been seeking.' So they went back retracing their footsteps, and found Kha,dir. (and) what happened further about them is narrated in the Holy Qur'an by Allah.\" (18.54 up to 18.82) "
    ,"The Prophet said, \"The example of guidance and knowledge with which Allah has sent me is like abundant rain falling on the earth, some of which was fertile soil that absorbed rain water and brought forth vegetation and grass in abundance. (And) another portion of it was hard and held the rain water and Allah benefited the people with it and they utilized it for drinking, making their animals drink from it and for irrigation of the land for cultivation. (And) a portion of it was barren which could neither hold the water nor bring forth vegetation (then that land gave no benefits). The first is the example of the person who comprehends Allah's religion and gets benefit (from the knowledge) which Allah has revealed through me (the Prophets and learns and then teaches others. The last example is that of a person who does not care for it and does not take Allah's guidance revealed through me (He is like that barren land.)\" "
    ," Allah's Apostle said, \"From among the portents of the Hour are (the following):\r\n\r\n1. Religious knowledge will be taken away (by the death of Religious learned men).\r\n\r\n2. (Religious) ignorance will prevail.\r\n\r\n3. Drinking of Alcoholic drinks (will be very common).\r\n\r\n4. There will be prevalence of open illegal sexual intercourse. "
    ," I will narrate to you a Hadith and none other than I will tell you about after it. I heard Allah's Apostle saying: From among the portents of the Hour are (the following):\r\n\r\n1. Religious knowledge will decrease (by the death of religious learned men).\r\n\r\n2. Religious ignorance will prevail.\r\n\r\n3. There will be prevalence of open illegal sexual intercourse.\r\n\r\n4. Women will increase in number and men will decrease in number so much so that fifty women will be looked after by one man. "
    ,"Allah's Apostle said, \"While I was sleeping, I saw that a cup full of milk was brought to me and I drank my fill till I noticed (the milk) its wetness coming out of my nails. Then I gave the remaining milk to 'Umar Ibn Al-Khattab\" The companions of the Prophet asked, \"What have you interpreted (about this dream)? \"O Allah's Apostle ,!\" he replied, \"(It is religious) knowledge.\" "
    ," Allah's Apostle stopped (for a while near the Jimar) at Mina during his last Hajj for the people and they were asking him questions. A man came and said, \"I forgot and got my head shaved before slaughtering the Hadi (sacrificing animal).\" The Prophet said, \"There is no harm, go and do the slaughtering now.\" Then another person came and said, \"I forgot and slaughtered (the camel) before Rami (throwing of the pebbles) at the Jamra.\" The Prophet said, \"Do the Rami now and there is no harm.\"\r\n\r\nThe narrator added: So on that day, when the Prophet was asked about anything (as regards the ceremonies of Hajj) performed before or after its due time, his reply was: \"Do it (now) and there is no harm.\" "
    ,"Somebody said to the Prophet (during his last Hajj), \"I did the slaughtering before doing the Rami.' The Prophet beckoned with his hand and said, \"There is no harm in that.\" Then another person said. \"I got my head shaved before offering the sacrifice.\" The Prophet beckoned with his hand saying, \"There is no harm in that.\" "
    ,"The Prophet said, \"(Religious) knowledge will be taken away (by the death of religious scholars) ignorance (in religion) and afflictions will appear; and Harj will increase.\" It was asked, \"What is Harj, O Allah's Apostle?\" He replied by beckoning with his hand indicating \"killing.\" (Fateh-al-Bari Page 192, Vol. 1) "
    ," I came to 'Aisha while she was praying, and said to her, \"What has happened to the people?\" She pointed out towards the sky. (I looked towards the mosque), and saw the people offering the prayer. Aisha said, \"Subhan Allah.\" I said to her, \"Is there a sign?\" She nodded with her head meaning, \"Yes.\" I, too, then stood (for the prayer of eclipse) till I became (nearly) unconscious and later on I poured water on my head. After the prayer, the Prophet praised and glorified Allah and then said,\r\n\r\n\"Just now at this place I have seen what I have never seen before, including Paradise and Hell. No doubt it has been inspired to me that you will be put to trials in your graves and these trials will be like the trials of Masiah-ad-Dajjal or nearly like it (the sub narrator is not sure which expression Asma' used). You will be asked, 'What do you know about this man (the Prophet Muhammad)?' Then the faithful believer (or Asma' said a similar word) will reply, 'He is Muhammad Allah's Apostle who had come to us with clear evidences and guidance and so we accepted his teachings and followed him. And he is Muhammad.' And he will repeat it thrice. Then the angels will say to him, 'Sleep in peace as we have come to know that you were a faithful believer.' On the other hand, a hypocrite or a doubtful person will reply, 'I do not know, but I heard the people saying something and so I said it.' (the same). \" "
    ,"'Uqba bin Al-Harith said that he had married the daughter of Abi Ihab bin 'Aziz. Later on a woman came to him and said, \"I have suckled (nursed) Uqba and the woman whom he married (his wife) at my breast.\" 'Uqba said to her, \"Neither I knew that you have suckled (nursed) me nor did you tell me.\" Then he rode over to see Allah's Apostle at Medina, and asked him about it. Allah's Apostle said, \"How can you keep her as a wife when it has been said (that she is your foster-sister)?\" Then Uqba divorced her, and she married another man. "
    ,"My Ansari neighbor from Bani Umaiya bin Zaid who used to live at 'Awali Al-Medina and used to visit the Prophet by turns. He used to go one day and I another day. When I went I used to bring the news of that day regarding the Divine Inspiration and other things, and when he went, he used to do the same for me. Once my Ansari friend, in his turn (on returning from the Prophet), knocked violently at my door and asked if I was there.\" I became horrified and came out to him. He said, \"Today a great thing has happened.\" I then went to Hafsa and saw her weeping. I asked her, \"Did Allah's Apostle divorce you all?\" She replied, \"I do not know.\" Then, I entered upon the Prophet and said while standing, \"Have you divorced your wives?\" The Prophet replied in the negative. On what I said, \"Allahu-Akbar (Allah is Greater).\" (See Hadith No. 119, Vol. 3 for details) "
    ,"Once a man said to Allah's Apostle \"O Allah's Apostle! I may not attend the (compulsory congregational) prayer because so and so (the Imam) prolongs the prayer when he leads us for it. The narrator added: \"I never saw the Prophet more furious in giving advice than he was on that day. The Prophet said, \"O people! Some of you make others dislike good deeds (the prayers). So whoever leads the people in prayer should shorten it because among them there are the sick the weak and the needy (having some jobs to do).\" "
    ,"A man asked the Prophet about the picking up of a \"Luqata\" (fallen lost thing). The Prophet replied, \"Recognize and remember its tying material and its container, and make public announcement (about it) for one year, then utilize it but give it to its owner if he comes.\" Then the person asked about the lost camel. On that, the Prophet got angry and his cheeks or his Face became red and he said, \"You have no concern with it as it has its water container, and its feet and it will reach water, and eat (the leaves) of trees till its owner finds it.\" The man then asked about the lost sheep. The Prophet replied, \"It is either for you, for your brother (another person) or for the wolf.\" "
    ,"The Prophet was asked about things which he did not like, but when the questioners insisted, the Prophet got angry. He then said to the people, \"Ask me anything you like.\" A man asked, \"Who is my father?\" The Prophet replied, \"Your father is Hudhafa.\" Then another man got up and said, \"Who is my father, O Allah's Apostle ?\" He replied, \"Your father is Salim, Maula (the freed slave) of Shaiba.\" So when 'Umar saw that (the anger) on the face of the Prophet he said, \"O Allah's Apostle! We repent to Allah (Our offending you).\" "
    ,"One day Allah's Apostle came out (before the people) and 'Abdullah bin Hudhafa stood up and asked (him) \"Who is my father?\" The Prophet replied, \"Your father is Hudhafa.\" The Prophet told them repeatedly (in anger) to ask him anything they liked. 'Umar knelt down before the Prophet and said thrice, \"We accept Allah as (our) Lord and Islam as (our) religion and Muhammad as (our) Prophet.\" After that the Prophet became silent. "
    ,"Whenever the Prophet asked permission to enter, he knocked the door thrice with greeting and whenever he spoke a sentence (said a thing) he used to repeat it thrice. (See Hadith No. 261, Vol. 8). "
    ,"Whenever the Prophet spoke a sentence (said a thing), he used to repeat it thrice so that the people could understand it properly from him and whenever he asked permission to enter, (he knocked the door) thrice with greeting. "
    ,"Once Allah's Apostle remained behind us in a journey. He joined us while we were performing ablution for the 'Asr prayer which was over-due. We were just passing wet hands over our feet (not washing them properly) so the Prophet addressed us in a loud voice and said twice or thrice, \"Save your heels from the fire.\" "
    ," Allah's Apostle said \"Three persons will have a double reward:\r\n\r\n1. A Person from the people of the scriptures who believed in his prophet (Jesus or Moses) and then believed in the Prophet Muhammad (i .e. has embraced Islam).\r\n\r\n2. A slave who discharges his duties to Allah and his master.\r\n\r\n3. A master of a woman-slave who teaches her good manners and educates her in the best possible way (the religion) and manumits her and then marries her.\" "
    ,"Once Allah's Apostle came out while Bilal was accompanying him. He went towards the women thinking that they had not heard him (i.e. his sermon). So he preached them and ordered them to pay alms. (Hearing that) the women started giving alms; some donated their ear-rings, some gave their rings and Bilal was collecting them in the corner of his garment."
    ,"I said: \"O Allah's Apostle! Who will be the luckiest person, who will gain your intercession on the Day of Resurrection?\" Allah's Apostle said: O Abu Huraira! \"I have thought that none will ask me about it before you as I know your longing for the (learning of) Hadiths. The luckiest person who will have my intercession on the Day of Resurrection will be the one who said sincerely from the bottom of his heart \"None has the right to be worshipped but Allah.\"\r\n\r\nAnd 'Umar bin 'Abdul 'Aziz wrote to Abu Bakr bin Hazm, \"Look for the knowledge of Hadith and get it written, as I am afraid that religious knowledge will vanish and the religious learned men will pass away (die). Do not accept anything save the Hadiths of the Prophet. Circulate knowledge and teach the ignorant, for knowledge does not vanish except when it is kept secretly (to oneself).\" "
    ,"also narrates the same (above-mentioned statement) as has been narrated by 'Umar bin 'Abdul 'Aziz up to \"The religious scholar (learned men) will pass away (die).\" "
    ,"I heard Allah's Apostle saying, \"Allah does not take away the knowledge, by taking it away from (the hearts of) the people, but takes it away by the death of the religious learned men till when none of the (religious learned men) remains, people will take as their leaders ignorant persons who when consulted will give their verdict without knowledge. So they will go astray and will lead the people astray.\""
    ,"Some women requested the Prophet to fix a day for them as the men were taking all his time. On that he promised them one day for religious lessons and commandments. Once during such a lesson the Prophet said, \"A woman whose three children die will be shielded by them from the Hell fire.\" On that a woman asked, \"If only two die?\" He replied, \"Even two (will shield her from the Hell-fire).\""
    ,"as above (the sub narrators are different). Abu Huraira qualified the three children referred to in the above mentioned Hadith as not having reached the age of committing sins (i.e. age of puberty)."
    ,"Whenever 'Aisha (the wife of the Prophet) heard anything which she did not understand, she used to ask again till she understood it completely. Aisha said: \"Once the Prophet said, \"Whoever will be called to account (about his deeds on the Day of Resurrection) will surely be punished.\" I said, \"Doesn't Allah say: \"He surely will receive an easy reckoning.\" (84.8) The Prophet replied, \"This means only the presentation of the accounts but whoever will be argued about his account, will certainly be ruined.\""
    ,"The Prophet said. No doubt your blood, property, the sub-narrator Muhammad thought that Abu Bakra had also mentioned and your honor (chastity), are sacred to one another as is the sanctity of this day of yours in this month of yours. It is incumbent on those who are present to inform those who are absent.\" (Muhammad the Subnarrator used to say, \"Allah's Apostle told the truth.\") The Prophet repeated twice: \"No doubt! Haven't I conveyed Allah's message to you."
    ,"The Prophet said, \"Do not tell a lie against me for whoever tells a lie against me (intentionally) then he will surely enter the Hell-fire.\""
    ,"I said to my father, 'I do not hear from you any narration (Hadith) of Allah s Apostle as I hear (his narrations) from so and so?\" Az-Zubair replied. l was always with him (the Prophet) and I heard him saying \"Whoever tells a lie against me (intentionally) then (surely) let him occupy, his seat in Hell-fire."
    ,"The fact which stops me from narrating a great number of Hadiths to you is that the Prophet said: \"Whoever tells a lie against me intentionally, then (surely) let him occupy his seat in Hell-fire.\""
    ,"I heard the Prophet saying, \"Whoever (intentionally) ascribes to me what I have not said then (surely) let him occupy his seat in Hell-fire.\""
    ,"The Prophet said, \"Name yourselves with my name (use my name) but do not name yourselves with my Kunya name (i.e. Abu-l Qasim). And whoever sees me in a dream then surely he has seen me for Satan cannot impersonate me. And whoever tells a lie against me (intentionally), then (surely) let him occupy his seat in Hell-fire.\""
    ,"Abu Juhaifa said, \"I asked Ali, 'Have you got any book (which has been revealed to the Prophet apart from the Qur'an)?' 'Ali replied, 'No, except Allah's Book or the power of understanding which has been bestowed (by Allah) upon a Muslim or what is (written) in this sheet of paper (with me).' Abu Juhaifa said, \"I asked, 'What is (written) in this sheet of paper?' Ali replied, it deals with The Diyya (compensation (blood money) paid by the killer to the relatives of the victim), the ransom for the releasing of the captives from the hands of the enemies, and the law that no Muslim should be killed in Qisas (equality in punishment) for the killing of (a disbeliever)."
    ,"There is none among the companions of the Prophet who has narrated more Hadiths than I except 'Abdallah bin Amr (bin Al-'As) who used to write them and I never did the same."
    ,"Ibn 'Abbas said, \"When the ailment of the Prophet became worse, he said, 'Bring for me (writing) paper and I will write for you a statement after which you will not go astray.' But 'Umar said, 'The Prophet is seriously ill, and we have got Allah's Book with us and that is sufficient for us.' But the companions of the Prophet differed about this and there was a hue and cry. On that the Prophet said to them, 'Go away (and leave me alone). It is not right that you should quarrel in front of me.\" Ibn 'Abbas came out saying, \"It was most unfortunate (a great disaster) that Allah's Apostle was prevented from writing that statement for them because of their disagreement and noise. (Note: It is apparent from this Hadith that Ibn 'Abbes had witnessed the event and came out saying this statement. The truth is not so, for Ibn 'Abbas used to say this statement on narrating the Hadith and he had not witnessed the event personally. See Fath Al-Bari Vol. 1, p.220 footnote.) (See Hadith No. 228, Vol. 4)."
    ,"One night Allah's Apostle got up and said, \"Subhan Allah! How many afflictions have been descended tonight and how many treasures have been disclosed! Go and wake the sleeping lady occupants of these dwellings (his wives) up (for prayers). A well-dressed (soul) in this world may be naked in the Hereafter. \""
    ,"Once the Prophet led us in the 'Isha' prayer during the last days of his life and after finishing it (the prayer) (with Taslim) he said: \"Do you realize (the importance of) this night?\" Nobody present on the surface of the earth tonight will be living after the completion of one hundred years from this night.\""
    ,"I stayed overnight in the house of my aunt Maimuna bint Al-Harith (the wife of the Prophet ) while the Prophet was there with her during her night turn. The Prophet offered the 'Isha' prayer (in the mosque), returned home and after having prayed four Rakat, he slept. Later on he got up at night and then asked whether the boy (or he used a similar word) had slept? Then he got up for the prayer and I stood up by his left side but he made me stand to his right and offered five Rakat followed by two more Rakat. Then he slept and I heard him snoring and then (after a while) he left for the (Fajr) prayer."
    ,"I said to Allah's Apostle \"I hear many narrations (Hadiths) from you but I forget them.\" Allah's Apostle said, \"Spread your Rida' (garment).\" I did accordingly and then he moved his hands as if filling them with something (and emptied them in my Rida') and then said, \"Take and wrap this sheet over your body.\" I did it and after that I never forgot any thing."
    ,"Ibn Abi Fudaik narrated the same as above (Hadith...119) but added that the Prophet had moved his hands as if filling them with something and then he emptied them in the Rida' of Abu Huraira. "
    ,"I have memorized two kinds of knowledge from Allah's Apostle . I have propagated one of them to you and if I propagated the second, then my pharynx (throat) would be cut (i.e. killed)."
    ,"The Prophet said to me during Hajjat-al-Wida': Let the people keep quiet and listen. Then he said (addressing the people), \"Do not (become infidels) revert to disbelief after me by striking the necks (cutting the throats) of one another (killing each other).\""
    ,"I said to Ibn 'Abbas, \"Nauf-Al-Bakali claims that Moses (the companion of Khadir) was not the Moses of Bani Israel but he was another Moses.\" Ibn 'Abbas remarked that the enemy of Allah (Nauf) was a liar."
    ,"A man came to the Prophet and asked, \"O Allah's Apostle! What kind of fighting is in Allah's cause? (I ask this), for some of us fight because of being enraged and angry and some for the sake of his pride and haughtiness.\" The Prophet raised his head (as the questioner was standing) and said, \"He who fights so that Allah's Word (Islam) should be superior, then he fights in Allah's cause.\""
    ,"I saw the Prophet near the Jamra and the people were asking him questions (about religious problems). A man asked, \"O Allah's Apostle! I have slaughtered the Hadi (animal) before doing the Rami.\" The Prophet replied, \"Do the Rami (now) and there is no harm.\" Another person asked, \"O Allah's Apostle! I got my head shaved before slaughtering the animal.\" The Prophet replied, \"Do the slaughtering (now) and there is no harm.\" So on that day, when the Prophet was asked about anything as regards the ceremonies of Hajj performed before or after its due time his reply was, \"Do it (now) and there is no harm.\" "
    ,"Ibn Az-Zubair said to me, \"Aisha used to tell you secretly a number of things. What did she tell you about the Ka'ba?\" I replied, \"She told me that once the Prophet said, 'O 'Aisha! Had not your people been still close to the pre-Islamic period of ignorance (infidelity)! I would have dismantled the Ka'ba and would have made two doors in it; one for entrance and the other for exit.\" Later on Ibn Az-Zubair did the same."
    ,"I was informed that the Prophet had said to Mu'adh, \"Whosoever will meet Allah without associating anything in worship with Him will go to Paradise.\" Mu'adh asked the Prophet, \"Should I not inform the people of this good news?\" The Prophet replied, \"No, I am afraid, lest they should depend upon it (absolutely).\" "
    ,"Um-Sulaim came to Allah's Apostle and said, \"Verily, Allah is not shy of (telling you) the truth. Is it necessary for a woman to take a bath after she has a wet dream (nocturnal sexual discharge?) The Prophet replied, \"Yes, if she notices a discharge.\" Um Salama, then covered her face and asked, \"O Allah's Apostle! Does a woman get a discharge?\" He replied, \"Yes, let your right hand be in dust (An Arabic expression you say to a person when you contradict his statement meaning \"you will not achieve goodness\"), and that is why the son resembles his mother.\""
    ,"Once Allah's Apostle said, \"Amongst the trees there is a tree, the leaves of which do not fall and is like a Muslim, tell me the name of that tree.\" Everybody started thinking about the trees of the desert areas and I thought of the date-palm tree but felt shy (to answer). The others asked, \"O Allah's Apostle! inform us of it.\" He replied, \"it is the date-palm tree.\" I told my father what had come to my mind and on that he said, \"Had you said it I would have preferred it to such and such a thing that I might possess.\" "
    ,"I used to get the emotional urethral discharge frequently so I requested Al-Miqdad to ask the Prophet about it. Al-Miqdad asked him and he replied, \"One has to perform ablution (after it).\" (See Hadith No. 269)."
    ,"'Abdullah bin 'Umar said: \"A man got up in the mosque and said: O Allah's Apostle 'At which place you order us that we should assume the Ihram?' Allah's Apostle replied, 'The residents of Medina should assure the Ihram from Dhil-Hulaifa, the people of Syria from Al-Ju,hfa and the people of Najd from Qarn.\" Ibn 'Umar further said, \"The people consider that Allah's Apostle had also said, 'The residents of Yemen should assume Ihram from Yalamlam.' \" Ibn 'Umar used to say, \"I do not: remember whether Allah's Apostle had said the last statement or not?\""
    ,"A man asked the Prophet : \"What (kinds of clothes) should a Muhrim (a Muslim intending to perform 'Umra or Hajj) wear? He replied, \"He should not wear a shirt, a turban, trousers, a head cloak or garment scented with saffron or Wars (kinds of perfumes). And if he has n slippers, then he can use Khuffs (leather socks) but the socks should be cut short so as to make the ankles bare.\" (See Hadith No. 615, Vol. 2)."
  ];

  String getHadith(at){
    return _hadith[at];
  }

  String getRef(at){
    return _ref[at];
  }

  int getOffsetLength(){
    return hadithLength;
  }
}